export const aiConfig = {
  title: 'Onur Gürsoy — AI & ML Engineer',
  eyebrow: 'Computer science / AI / machine learning',
  heading: 'AI Engineer',
  introduction: 'Building intelligent systems for real-world problems, from reinforcement learning in logistics to neural audio analysis.',
  labels: { featured: 'Featured projects', other: 'Other projects', experience: 'Professional experience', experienceIntro: 'Software engineering across logistics, event technology, legal tech, mobility and research.', problem: 'The problem', solution: 'The approach', connect: 'Find me online' },
  skills: ['Python', 'PyTorch', 'TensorFlow', 'Scikit-learn', 'TypeScript', 'React', 'Angular', 'Node.js', 'Docker', 'Git', 'SQL', 'REST APIs', 'Reinforcement Learning', 'Computer Vision', 'NLP', 'LLMs'],
  projects: [
    {
      title: 'Discrete-Event Simulation for Intermodal Rail Transshipment',
      description: 'Master thesis at EUROGATE comparing MILP-based planning with Q-Learning control for rail logistics.',
      problem: 'Intermodal terminals face complex scheduling challenges across crane usage, delays and container dwell times.',
      solution: 'Built a discrete-event simulation to compare traditional MILP optimization against a Q-Learning agent.',
      techStack: ['Python', 'SimPy', 'PyTorch', 'Gurobi', 'Reinforcement Learning', 'Q-Learning', 'MILP', 'NumPy', 'Pandas', 'Matplotlib'],
      github: 'https://github.com/OnurGuersoy', featured: true,
    },
    {
      title: 'Neural Drum Transcription',
      description: 'Audio-to-MIDI drum transcription using deep learning.',
      problem: 'Manual drum transcription is time-consuming and requires specialist musical knowledge.',
      solution: 'Designed a CNN-based spectrogram pipeline for drum onset detection and instrument classification.',
      techStack: ['Python', 'PyTorch', 'Librosa', 'MIDI', 'CNN', 'Audio Processing', 'NumPy', 'Scikit-learn'],
      github: 'https://github.com/OnurGuersoy', featured: true,
    },
    {
      title: 'LLM Fine-Tuning Pipeline',
      description: 'Pipeline for adapting language models to domain-specific tasks.',
      problem: 'Teams need repeatable tooling for data preparation, fine-tuning and evaluation.',
      solution: 'Designed a pipeline for LoRA/QLoRA fine-tuning, data curation and evaluation.',
      techStack: ['Python', 'PyTorch', 'Hugging Face Transformers', 'LoRA', 'PEFT', 'Weights & Biases', 'Docker'],
      github: 'https://github.com/OnurGuersoy', featured: true,
    },
    {
      title: 'Real-Time Object Detection System',
      description: 'Computer vision for real-time detection in industrial environments.',
      problem: 'Industrial visual inspection needs fast and accurate detection with low latency.',
      solution: 'Developed a YOLO-based detector with training and optimization for edge deployment.',
      techStack: ['Python', 'TensorFlow', 'YOLO', 'OpenCV', 'TensorRT', 'Docker', 'ONNX'],
      github: 'https://github.com/OnurGuersoy', featured: false,
    },
  ],
  experiences: [
    {
      company: 'EUROGATE GmbH & Co. KGaA, KG',
      role: 'Software / AI Engineer · Working student',
      duration: 'Jan 2024 – Aug 2026',
      techStack: ['Angular', 'Python', 'Discrete-event simulation', 'MILP', 'Q-Learning'],
      highlights: [
        'Developed the Angular frontend for railmybox.',
        'Researched intermodal rail-transshipment planning for a master’s thesis.',
        'Built a discrete-event simulation comparing MILP-based planning with Q-Learning control.',
      ],
    },
    {
      company: 'Event Inc Group',
      role: 'Software Engineer · Full-time',
      duration: 'Jun 2021 – Aug 2023',
      techStack: ['React'],
      highlights: [
        'Developed React frontend features for an events platform.',
        'Contributed to feature planning and architectural definition.',
        'Implemented features based on the agreed architecture.',
      ],
    },
    {
      company: 'Legal Analytics / Juracus',
      role: 'Full-stack Developer · Working student',
      duration: 'Oct 2020 – Apr 2021',
      techStack: [],
      highlights: ['Worked on full-stack development for a legal-technology platform.'],
    },
    {
      company: 'Movingdots GmbH',
      role: 'Full-stack Developer · Working student',
      duration: 'Feb 2020 – Sep 2020',
      techStack: [],
      highlights: ['Contributed to full-stack software development.'],
    },
    {
      company: 'Audi AG / Audi Electronic Ventures GmbH',
      role: 'Mobile Software Developer · Internship',
      duration: 'Jun 2019 – Nov 2019',
      techStack: [],
      highlights: ['Developed mobile application software during an internship.'],
    },
    {
      company: 'CTS Eventim',
      role: 'Test Automation Engineer · Working student',
      duration: 'May 2018 – Jun 2019',
      techStack: [],
      highlights: ['Worked on test automation for a ticketing platform.'],
    },
    {
      company: 'Universität Bremen',
      role: 'Media Informatics Tutor · Working student',
      duration: 'Nov 2017 – Mar 2018',
      techStack: [],
      highlights: ['Tutored students in media informatics.'],
    },
  ],
} as const;
