export const aiConfig = {
  title: 'Onur Gürsoy — AI & ML Engineer',
  eyebrow: 'Computer science / AI / machine learning',
  heading: 'AI Engineer',
  introduction: 'Building intelligent systems for real-world problems, from reinforcement learning in logistics to neural audio analysis.',
  labels: { featured: 'Featured projects', other: 'Other projects', experience: 'Experience', problem: 'The problem', solution: 'The approach', connect: 'Find me online' },
  skills: ['Python', 'PyTorch', 'TensorFlow', 'Scikit-learn', 'TypeScript', 'React', 'Angular', 'Node.js', 'Docker', 'Git', 'SQL', 'REST APIs', 'Reinforcement Learning', 'Computer Vision', 'NLP', 'LLMs'],
  projects: [
    {
      title: 'Discrete-Event Simulation for Intermodal Rail Transshipment',
      description: 'Master thesis at EUROGATE comparing MILP-based planning with Q-Learning control for rail logistics.',
      problem: 'Intermodal terminals face complex scheduling challenges across crane usage, delays and container dwell times.',
      solution: 'Built a discrete-event simulation to compare traditional MILP optimization against a Q-Learning agent.',
      techStack: ['Python', 'SimPy', 'PyTorch', 'Gurobi', 'Reinforcement Learning', 'Q-Learning', 'MILP', 'NumPy', 'Pandas', 'Matplotlib'],
      github: 'https://github.com/OnurGuersoy', featured: true,
    },
    {
      title: 'Neural Drum Transcription',
      description: 'Audio-to-MIDI drum transcription using deep learning.',
      problem: 'Manual drum transcription is time-consuming and requires specialist musical knowledge.',
      solution: 'Designed a CNN-based spectrogram pipeline for drum onset detection and instrument classification.',
      techStack: ['Python', 'PyTorch', 'Librosa', 'MIDI', 'CNN', 'Audio Processing', 'NumPy', 'Scikit-learn'],
      github: 'https://github.com/OnurGuersoy', featured: true,
    },
    {
      title: 'LLM Fine-Tuning Pipeline',
      description: 'Pipeline for adapting language models to domain-specific tasks.',
      problem: 'Teams need repeatable tooling for data preparation, fine-tuning and evaluation.',
      solution: 'Designed a pipeline for LoRA/QLoRA fine-tuning, data curation and evaluation.',
      techStack: ['Python', 'PyTorch', 'Hugging Face Transformers', 'LoRA', 'PEFT', 'Weights & Biases', 'Docker'],
      github: 'https://github.com/OnurGuersoy', featured: true,
    },
    {
      title: 'Real-Time Object Detection System',
      description: 'Computer vision for real-time detection in industrial environments.',
      problem: 'Industrial visual inspection needs fast and accurate detection with low latency.',
      solution: 'Developed a YOLO-based detector with training and optimization for edge deployment.',
      techStack: ['Python', 'TensorFlow', 'YOLO', 'OpenCV', 'TensorRT', 'Docker', 'ONNX'],
      github: 'https://github.com/OnurGuersoy', featured: false,
    },
  ],
  experience: [
    { company: 'EUROGATE GmbH & Co. KGaA, KG', role: 'Software-/AI Engineer (Working Student)', period: '01/2024 – 08/2026', highlights: ['railmybox Angular frontend development', 'Master thesis: simulation for intermodal rail transshipment, comparing MILP planning and Q-Learning control'] },
    { company: 'Event Inc Group', role: 'Software Engineer (Full-time)', period: '06/2021 – 08/2023', highlights: ['React frontend development', 'Feature planning and architectural implementation'] },
    { company: 'Legal Analytics / Juracus', role: 'Fullstack Developer (Working Student)', period: '10/2020 – 04/2021', highlights: ['Fullstack development for a legal tech platform'] },
    { company: 'Movingdots GmbH', role: 'Fullstack Developer (Working Student)', period: '02/2020 – 09/2020', highlights: ['Fullstack development'] },
    { company: 'Audi AG / Audi Electronic Ventures GmbH', role: 'Mobile Software Developer (Internship)', period: '06/2019 – 11/2019', highlights: ['Mobile application development'] },
    { company: 'CTS Eventim', role: 'Test Automation Engineer (Working Student)', period: '05/2018 – 06/2019', highlights: ['Test automation for a ticketing platform'] },
    { company: 'Universität Bremen', role: 'Tutor for Media Informatics (Working Student)', period: '11/2017 – 03/2018', highlights: ['Teaching and tutoring'] },
  ],
} as const;
