export const aiConfig = {
  title: 'Onur Gürsoy — AI & ML Engineer',
  eyebrow: 'Computer science / AI / machine learning',
  heading: 'AI Engineer',
  introduction: 'Building intelligent systems for real-world problems, from reinforcement learning in logistics to neural audio analysis.',
  labels: { featured: 'Featured projects', other: 'Other projects', experience: 'Professional experience', experienceIntro: 'Software engineering across logistics, event technology, legal tech, mobility and research.', problem: 'The problem', solution: 'The approach', connect: 'Find me online' },
  skills: ['Python', 'PyTorch', 'TensorFlow', 'Scikit-learn', 'TypeScript', 'React', 'Angular', 'Node.js', 'Docker', 'Git', 'SQL', 'REST APIs', 'Reinforcement Learning', 'NLP', 'LLMs', 'Realtime Simulation'],
  projects: [
    {
      title: 'Discrete-Event Simulation for Intermodal Rail Transshipment',
      description: 'Master thesis at EUROGATE comparing MILP-based planning with Q-Learning control for rail logistics.',
      problem: 'Intermodal terminals face complex scheduling challenges across crane usage, delays and container dwell times.',
      solution: 'Built a discrete-event simulation to compare traditional MILP optimization against a Q-Learning agent.',
      techStack: ['Python', 'SimPy', 'PyTorch', 'Gurobi', 'Reinforcement Learning', 'Q-Learning', 'MILP', 'NumPy', 'Pandas', 'Matplotlib'],
      github: 'https://github.com/OnurGuersoy', featured: true,
    },
    {
      title: 'Neural Drum Transcription',
      description: 'Audio-to-MIDI drum transcription using deep learning.',
      problem: 'Manual drum transcription is time-consuming and requires specialist musical knowledge.',
      solution: 'Designed a CNN-based spectrogram pipeline for drum onset detection and instrument classification.',
      techStack: ['Python', 'PyTorch', 'Librosa', 'MIDI', 'CNN', 'Audio Processing', 'NumPy', 'Scikit-learn'],
      github: 'https://github.com/OnurGuersoy', featured: true,
    },
    {
      title: 'LLM Fine-Tuning Pipeline',
      description: 'Pipeline for adapting language models to domain-specific tasks.',
      problem: 'Teams need repeatable tooling for data preparation, fine-tuning and evaluation.',
      solution: 'Designed a pipeline for LoRA/QLoRA fine-tuning, data curation and evaluation.',
      techStack: ['Python', 'PyTorch', 'Hugging Face Transformers', 'LoRA', 'PEFT', 'Weights & Biases', 'Docker'],
      github: 'https://github.com/OnurGuersoy', featured: true,
    },
  ],
  experiences: [
    {
      company: 'EUROGATE GmbH & Co. KGaA, KG',
      role: 'Software / AI Engineer · Working student',
      duration: 'Jan 2024 – Aug 2026',
      techStack: ['Angular', 'Python', 'Discrete-event simulation', 'MILP', 'Q-Learning'],
      highlights: [
        'Developed the Angular frontend for railmybox.',
        'Researched intermodal rail-transshipment planning for a master’s thesis.',
        'Built a discrete-event simulation comparing MILP-based planning with Q-Learning control.',
      ],
    },
    {
      company: 'Event Inc Group',
      role: 'Software Engineer · Full-time',
      duration: 'Jun 2021 – Aug 2023',
      techStack: ['React', 'NextJS', 'GraphQL', 'Ruby on Rails', 'Django', 'MariaDB', 'AWS'],
      highlights: [
        'Woking on a productive webapplication with a revenue stream of over a million Euros a year. Working close to regular users to refine the product inside a SCRUM based process. Mostly developing new features in React and NextJS on frontend utilizing GraphQL, Ruby on Rails and MariaDB on backend.'
      ],
    },
    {
      company: 'Legal Analytics / Juracus',
      role: 'Full-stack Developer · Working student',
      duration: 'Oct 2020 – Apr 2021',
      techStack: ['AngularJS', 'Java Spring Boot', 'AWS'],
      highlights: ['I was responsible for the real time webapplication frontend and backend using Angular and Spring Boot hosted on AWS Cloud and utilizing Websockets. Furthermore I developed and published a Typescript (legal-analytics-sdk on npm) and Java SDK (com.juracus.api on maven central) to access REST API services easily'],
    },
    {
      company: 'Movingdots GmbH',
      role: 'Full-stack Developer · Working student',
      duration: 'Feb 2020 – Sep 2020',
      techStack: ['React', 'Azure', '.NET'],
      highlights: ['Worked on user dashboards using React, Redux with Typscript and enhanced Microservice architectured Rest-Apis with .NET Core hosted on Azure Cloud.'],
    },
    {
      company: 'Audi AG / Audi Electronic Ventures GmbH',
      role: 'Mobile Software Developer · Internship',
      duration: 'Jun 2019 – Nov 2019',
      techStack: ['SwiftUI', 'Swift', 'UIKit'],
      highlights: ['Development of iOS mobile applications with UIKit, SwiftUI, Combine. Using MVVM and MVC architectures and SOLID principles.'],
    },
    {
      company: 'CTS Eventim',
      role: 'Test Automation Engineer · Working student',
      duration: 'May 2018 – Jun 2019',
      techStack: ['AutoHotkey'],
      highlights: ['Worked on test automation for a ticketing platform.'],
    },
    {
      company: 'Universität Bremen',
      role: 'Media Informatics Tutor · Working student',
      duration: 'Nov 2017 – Mar 2018',
      techStack: [],
      highlights: ['Tutored students in media informatics.'],
    },
  ],
} as const;
