export type Show = { date: string; city: string; venue: string; band: string; role: string; title?: string; description?: string; videoUrl?: string; image?: string };

export const musicConfig = {
  title: 'Onur Gürsoy — Drummer',
  eyebrow: 'Touring / session drummer',
  introduction: 'Live drums for RAUM27 and Chaos und Liebe. Substitute drummer for Remote Bondage and Vladi Wostock.',
  heroImage: '/website/images/drumming-crowd-view.jpg',
  labels: { featured: 'Selected live work', gallery: 'On stage', videos: 'Watch & listen', acts: 'Associated acts', credits: 'Selected recording credits', equipment: 'Live & studio setup', past: 'Selected past shows & sessions', back: 'Back to music', upcoming: 'Other upcoming shows', source: 'Dates and venues: Reservix tour announcement. Check the ticket page for availability.' },
  availability: 'Available for touring, session work and remote recording.',
  tourTitle: 'RAUM27 · Spring 2027',
  tourSubtitle: '17 dates · Germany & Austria',
  tourIntro: 'The largest RAUM27 tour yet. Full live band, 17 dates across Germany and Austria.',
  tourAction: 'All tour dates',
  ticketsLabel: 'Tickets at Reservix',
  ticketUrl: 'https://reservix.de/tickets-raum27/t16741',
  tourSource: 'https://www.reservix.net/presse/raum27-kuendigen-groesste-tour-ihrer-karriere-an/',
  tour: [
    { date: '2027-03-17', city: 'Saarbrücken', venue: 'Garage' },
    { date: '2027-03-18', city: 'Freiburg', venue: 'Jazzhaus' },
    { date: '2027-03-19', city: 'Nürnberg', venue: 'Hirsch' },
    { date: '2027-03-20', city: 'Fulda', venue: 'Kreuz' },
    { date: '2027-03-27', city: 'Hamburg', venue: 'Große Freiheit 36' },
    { date: '2027-04-02', city: 'Münster', venue: 'Skaters Palace' },
    { date: '2027-04-03', city: 'Wiesbaden', venue: 'Schlachthof' },
    { date: '2027-04-08', city: 'Wien', venue: 'WUK' },
    { date: '2027-04-09', city: 'Stuttgart', venue: 'Im Wizemann Halle' },
    { date: '2027-04-10', city: 'München', venue: 'Backstage Werk' },
    { date: '2027-04-11', city: 'Konstanz', venue: 'Kulturladen' },
    { date: '2027-04-15', city: 'Berlin', venue: 'Huxleys' },
    { date: '2027-04-16', city: 'Leipzig', venue: 'Felsenkeller' },
    { date: '2027-04-17', city: 'Kiel', venue: 'Die Pumpe' },
    { date: '2027-04-22', city: 'Oldenburg', venue: 'Kulturetage' },
    { date: '2027-04-23', city: 'Köln', venue: 'Carlswerk Victoria' },
    { date: '2027-04-24', city: 'Hannover', venue: 'Capitol' },
  ],
  acts: [
    { name: 'RAUM27', role: 'Live drums' },
    { name: 'Chaos und Liebe', role: 'Live band' },
    { name: 'Useful (Seven Seals)', role: 'Own band' },
    { name: 'Remote Bondage', role: 'Substitute drums' },
    { name: 'Vladi Wostock', role: 'Substitute drums' },
    { name: 'Nils Wandrey', role: 'Session work' },
    { name: 'shedancedslowly', role: 'Live / session' },
  ],
  credits: [
    { title: 'Anfangen Anzufangen', kind: 'Album', artist: 'RAUM27', detail: 'Album instrumentation / drums', url: 'https://hb-people.de/bilder/raum27-veroeffentlichen-debuet-album-anfangen-anzufangen/' },
    { title: 'Das Klima wieder hin', kind: 'Single', artist: 'RAUM27', detail: 'Drums — credit supplied by Onur' },
  ],
  pastShows: [
    { date: '2025-03-21', city: 'Hamburg', venue: 'Markthalle', band: 'RAUM27', role: 'Live drums', title: 'Keine Tränen Tour', description: 'Sold-out Hamburg concert, including an Onur drum solo.', videoUrl: 'https://www.soundsandbooks.com/raum27-live-in-hamburg-2025/' },
    { date: '2026-09-20', city: 'Hamburg', venue: 'Große Freiheit 36', band: 'Chaos und Liebe', role: 'Live band drummer', title: 'Chaos und Liebe — Live Band Tour', description: 'Live band performance.', image: '/website/images/drumming-behind-kit.jpg' },
    { date: '2026-06-10', city: 'Remote', venue: 'Session', band: 'Remote Bondage', role: 'Substitute drummer', title: 'Remote Bondage — Substitute Drums', description: 'Substitute drumming for selected performances and sessions.' },
    { date: '2026-04-22', city: 'Hamburg', venue: 'Studio / Live', band: 'Vladi Wostock', role: 'Substitute drummer', title: 'Vladi Wostock — Collaboration', description: 'Substitute drumming for selected performances.' },
    { date: '2026-03-15', city: 'Hamburg', venue: 'Studio Session', band: 'Nils Wandrey', role: 'Session drummer', title: 'Nils Wandrey — Session Work', description: 'Drum tracking for a solo project.' },
    { date: '2026-02-28', city: 'Hamburg', venue: 'Knust', band: 'shedancedslowly', role: 'Session drummer', title: 'shedancedslowly — Live Performance', description: 'Live performance with shedancedslowly.' },
  ] satisfies Show[],
  videos: [
    { title: 'RAUM27 — Live Performance', url: 'https://www.youtube.com/watch?v=o3NOqJbsDgM', type: 'youtube' as const },
    { title: 'RAUM27 — ZDF Morgenmagazin Feature', url: 'https://www.zdfheute.de/video/zdf-morgenmagazin/raum-100.html', type: 'external' as const },
    { title: 'Live Session — Full Band', url: 'https://www.youtube.com/watch?v=Lkt6So1wYT4', type: 'youtube' as const },
    { title: 'Drum Performance', url: 'https://www.youtube.com/watch?v=VlDAqgDOYMs', type: 'youtube' as const },
    { title: 'Live Set — Behind the Kit', url: 'https://www.youtube.com/watch?v=njGE0_wAK_E', type: 'youtube' as const },
  ],
  gallery: [
    { src: '/website/images/drumming-stage-smoke.jpg', alt: 'Drumming on stage with smoke' },
    { src: '/website/images/drumming-behind-kit.jpg', alt: 'Behind the drum kit' },
    { src: '/website/images/drumming-crowd-view.jpg', alt: 'View from behind the drums to the crowd' },
    { src: '/website/images/drumming-sticks-portrait.jpg', alt: 'Onur holding drumsticks' },
  ],
  equipment: 'Acoustic drums with Roland SPD-SX sampling pad and electronic triggers. In-ear monitoring for live performances and remote recording setup.',
  epk: {
    eyebrow: 'For bookers & collaborators',
    title: 'Electronic press kit',
    description: 'The essentials for a booking: live work, selected recordings, footage, photographs and contact in one place.',
    action: 'Download EPK',
    downloadUrl: '/assets/Onur_Guersoy_EPK.pdf',
    contactAction: 'Enquire about a booking',
  },
} as const;
